name = "character-chat-worker"
main = "src/index.ts"
compatibility_date = "2026-04-01"

[vars]
GOOGLE_WEB_CLIENT_ID = "1081775489416-m4hjl4vususc5e31n9dnvu3r2std0uia.apps.googleusercontent.com"
OPENROUTER_MODEL = "openrouter/auto"
FAL_MODEL = "fal-ai/flux/dev"
R2_PUBLIC_BASE_URL = "https://pub-295477e9e5cb466c90c9c4df663d67fc.r2.dev"

[[d1_databases]]
binding = "DB"
database_name = "character-chat"
database_id = "ad611737-fc84-4002-bcfe-0f0ce257f2ae"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "character-chat-assets"

